// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: flight_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlightServiceClient is the client API for FlightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightServiceClient interface {
	CancelBooking(ctx context.Context, in *BookingCancellationRequest, opts ...grpc.CallOption) (*BookingCancellationResponse, error)
	BookTicket(ctx context.Context, in *BookTicketRequest, opts ...grpc.CallOption) (*BookTicketResponse, error)
	ChangeBooking(ctx context.Context, in *ChangeBookingRequest, opts ...grpc.CallOption) (*ChangeBookingResponse, error)
}

type flightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightServiceClient(cc grpc.ClientConnInterface) FlightServiceClient {
	return &flightServiceClient{cc}
}

func (c *flightServiceClient) CancelBooking(ctx context.Context, in *BookingCancellationRequest, opts ...grpc.CallOption) (*BookingCancellationResponse, error) {
	out := new(BookingCancellationResponse)
	err := c.cc.Invoke(ctx, "/proto.FlightService/CancelBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) BookTicket(ctx context.Context, in *BookTicketRequest, opts ...grpc.CallOption) (*BookTicketResponse, error) {
	out := new(BookTicketResponse)
	err := c.cc.Invoke(ctx, "/proto.FlightService/BookTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) ChangeBooking(ctx context.Context, in *ChangeBookingRequest, opts ...grpc.CallOption) (*ChangeBookingResponse, error) {
	out := new(ChangeBookingResponse)
	err := c.cc.Invoke(ctx, "/proto.FlightService/ChangeBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightServiceServer is the server API for FlightService service.
// All implementations must embed UnimplementedFlightServiceServer
// for forward compatibility
type FlightServiceServer interface {
	CancelBooking(context.Context, *BookingCancellationRequest) (*BookingCancellationResponse, error)
	BookTicket(context.Context, *BookTicketRequest) (*BookTicketResponse, error)
	ChangeBooking(context.Context, *ChangeBookingRequest) (*ChangeBookingResponse, error)
	MustEmbedUnimplementedFlightServiceServer()
}

// UnimplementedFlightServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlightServiceServer struct {
}

func (UnimplementedFlightServiceServer) CancelBooking(context.Context, *BookingCancellationRequest) (*BookingCancellationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedFlightServiceServer) BookTicket(context.Context, *BookTicketRequest) (*BookTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookTicket not implemented")
}
func (UnimplementedFlightServiceServer) ChangeBooking(context.Context, *ChangeBookingRequest) (*ChangeBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeBooking not implemented")
}
func (UnimplementedFlightServiceServer) MustEmbedUnimplementedFlightServiceServer() {}

// UnsafeFlightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightServiceServer will
// result in compilation errors.
type UnsafeFlightServiceServer interface {
	MustEmbedUnimplementedFlightServiceServer()
}

func RegisterFlightServiceServer(s grpc.ServiceRegistrar, srv FlightServiceServer) {
	s.RegisterService(&FlightService_ServiceDesc, srv)
}

func _FlightService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCancellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FlightService/CancelBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).CancelBooking(ctx, req.(*BookingCancellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_BookTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).BookTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FlightService/BookTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).BookTicket(ctx, req.(*BookTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_ChangeBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).ChangeBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FlightService/ChangeBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).ChangeBooking(ctx, req.(*ChangeBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightService_ServiceDesc is the grpc.ServiceDesc for FlightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FlightService",
	HandlerType: (*FlightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelBooking",
			Handler:    _FlightService_CancelBooking_Handler,
		},
		{
			MethodName: "BookTicket",
			Handler:    _FlightService_BookTicket_Handler,
		},
		{
			MethodName: "ChangeBooking",
			Handler:    _FlightService_ChangeBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flight_service.proto",
}
